routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'HomeController@index')->name('home');
/**/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard','HomeController@index')->name('home');
    //Information
    Route::get('information', ['as' => 'information.edit', 'uses' => 'InformationController@edit']);
    Route::patch('information', ['as' => 'information.update', 'uses' => 'InformationController@update']);
    //Profile
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::patch('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::post('check-old-pwd','ProfileController@checkOldPassword')->name('checkOldPassword');
    Route::post('update-old-pwd','ProfileController@updateOldPassword')->name('updateOldPassword');
    //Patient
    Route::resource('patients','PatientController');
    Route::get('print/patients/{patient}', ['as' => 'patients.print', 'uses' => 'PatientController@printPatient']);
    Route::get('patients/export/{patient}', 'PatientController@export')->name('patientExport');

});


Auth::routes([
    'register' => false, // Registration Routes...
]);


Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/backend/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">&copy; {{ now()->year }} <a href="https://rarait.com" class="font-weight-bold ml-1" target="_blank">Rara IT</a></span>
    </div>
</footer>

resources/views/layouts/backend/header.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
            <a class="navbar-brand brand-logo" href="index.html"><img src="{{asset('admin/images/logo.svg')}}" alt="logo"/></a>
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{asset('admin/images/logo-mini.svg')}}" alt="logo"/></a>
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-sort-variant"></span>
            </button>
        </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">

        <ul class="navbar-nav navbar-nav-right">

            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                    <img src="{{asset('admin/images/user/'.auth()->user()->image)}}" alt="profile"/>
                    <span class="nav-profile-name">{{auth()->user()->name }}  </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="{{route('profile.edit')}}">
                        <i class="mdi mdi-settings text-primary"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="{{route('logout')}}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout text-primary"></i>
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

resources/views/layouts/backend/script.blade.php
<script src="{{asset('admin/vendors/base/vendor.bundle.base.js')}}"></script>

<script src="{{asset('admin/vendors/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('admin/vendors/datatables.net/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>

<script src="{{asset('admin/js/off-canvas.js')}}"></script>
<script src="{{asset('admin/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('admin/js/template.js')}}"></script>

<script src="{{asset('admin/js/dashboard.js')}}"></script>
<script src="{{asset('admin/js/data-table.js')}}"></script>
<script src="{{asset('admin/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/js/dataTables.bootstrap4.js')}}"></script>

<script src="{{asset('admin/js/jquery.cookie.js')}}" type="text/javascript"></script>
<script src="{{asset('js/custom.js')}}"></script>

@yield('script')

resources/views/layouts/backend/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{url('dashboard')}}">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">{{ __('Dashboard') }}</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{route('profile.edit')}}">
                <i class="mdi mdi-account menu-icon"></i>
                <span class="menu-title">{{ __('Profile') }}</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('information.edit')}}">
                <i class="mdi mdi-home-variant menu-icon"></i>
                <span class="menu-title">{{ __('Office Profile') }}</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('patients.index')}}">
                <i class="mdi mdi-emoticon menu-icon"></i>
                <span class="menu-title">{{ __('Patients') }}</span>
            </a>
        </li>

    </ul>
</nav>

resources/views/layouts/backend/style.blade.php
<link rel="stylesheet" href="{{asset('admin/vendors/mdi/css/materialdesignicons.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/vendors/base/vendor.bundle.base.css')}}">
<!-- endinject -->
<!-- plugin css for this page -->
<link rel="stylesheet" href="{{asset('admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="{{asset('admin/css/style.css')}}">
<!-- endinject -->
<link rel="shortcut icon" href="{{asset('admin/images/favicon.png')}}" />
<link href="{{asset('css/custom.css')}}" rel="stylesheet">
@yield('style')