routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'HomeController@index')->name('home');
/**/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard','HomeController@index')->name('home');
    //Information
    Route::get('information', ['as' => 'information.edit', 'uses' => 'InformationController@edit']);
    Route::patch('information', ['as' => 'information.update', 'uses' => 'InformationController@update']);
    //Profile
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::patch('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::post('check-old-pwd','ProfileController@checkOldPassword')->name('checkOldPassword');
    Route::post('update-old-pwd','ProfileController@updateOldPassword')->name('updateOldPassword');
    //Patient
    Route::resource('patients','PatientController');
    Route::get('print/patients/{patient}', ['as' => 'patients.print', 'uses' => 'PatientController@printPatient']);
    Route::get('patients/export/{patient}', 'PatientController@export')->name('patientExport');

});


Auth::routes([
    'register' => false, // Registration Routes...
]);


Route::get('/home', 'HomeController@index')->name('home');

app/Patient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Filterable;

class Patient extends Model
{
    use Filterable;
    protected $fillable = [
        'name','name','age','sex','marital_status','nationality','pp_no','apply_county','pp_issue_date', 'pp_issue_place', 'recruiting_agency'
        ,'history_illness','height','weight','temp', 'pulse', 'bp', 'clubbing'
        ,'jaundice','oedema','paller','ascites','allergy','cyanosis','lymph_node','fungal_infection','depression'
        ,'right_eye','left_eye','color_vision','right_ear','left_ear','cardiovascular','pulmonary','gastroenterology','neurology','musculoskeletal','genitourinary'
        ,'oro_dental','extremities','varicose_veins','hernia','hydrocele','radiological','ecg','heart','lungs','abdomen','clinical_impression'
        ,'anti_hiv', 'hbs_ag', 'anti_hcv', 'vdrl', 'tpha', 'blood_group', 'rbc', 'pus_ceils', 'bacteria', 'opiates', 'epithelial_cells', 'pregnancy_test'
        ,'total_wbc_count', 'neutrophils', 'lymphocytes', 'eosinophils', 'monocytes', 'basophils', 'esr', 'hemoglobin', 'malaria_parasite', 'micro_filaria'
        ,'random_blood_sugar','urea','creatinine','bilirubin','sgpt','sgot','others','cannabis','mantoux_test'
        ,'image','medical_examination_date','status','emc_code'
    ];
    protected $dates = ['medical_examination_date'];
   /* protected $casts = [''];*/

    public function image(){

        return 'admin/images/patients/'.$this->image;
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\PatientsDataTable;
use App\Exports\PatientExport;
use App\Http\Requests\PatientRequest;
use App\Patient;
use Illuminate\Http\Request;
use Image;
use File;
use Maatwebsite\Excel\Facades\Excel;

class PatientController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request,PatientsDataTable $dataTable)
    {
        $activefilters = $request->all();

        return $dataTable->render('patients.index',compact('activefilters'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('patients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Patient $patient,PatientRequest $request)
    {
        $patient->fill($request->all());
        if($request->hasFile('patient_image')){
            $image_tmp=$request->file('patient_image');

            if($image_tmp->isValid()){
                $image_name=$image_tmp->getClientOriginalName();

                $extension=$image_tmp->getClientOriginalExtension();

                $imageName=$image_name.'-'.rand(111,99999).'.'.$extension;

                $image_path='admin/images/patients/'.$imageName;
                Image::make($image_tmp)->save($image_path);
            }
        }
        $patient->image=$imageName;

        $patient->save();

         return redirect()->route('patients.index')->with('flash_success_message','New Patient Record has been Created');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function show(Patient $patient)
    {
        return view('patients.show',compact('patient'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient)
    {
        return view('patients.edit',compact('patient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function update(PatientRequest $request, Patient $patient)
    {

        $patient->fill($request->all());
        if($request->hasFile('patient_image')){
            $image_tmp=$request->file('patient_image');

            $image_path = $patient->image();

            if(File::exists($image_path)){
                File::delete($image_path);
            }

            if($image_tmp->isValid()){
                $image_name=$image_tmp->getClientOriginalName();

                $extension=$image_tmp->getClientOriginalExtension();

                $imageName=$image_name.'-'.rand(111,99999).'.'.$extension;

                $image_path='admin/images/patients/'.$imageName;

                Image::make($image_tmp)->save($image_path);
                $patient->image=$imageName;
            }
        }
        $patient->update();
        return redirect()->route('patients.index')->with('flash_success_message','Patient Record has been Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Patient $patient)
    {
        if(!empty($patient->image))
            $image_path = $patient->image();
        if(File::exists($image_path)){
            File::delete($image_path);
        }

         $patient->delete();

        return redirect()->route('patients.index')->with('flash_success_message','Patient Record has been Deleted');

    }
    public function printPatient(Patient $patient){

        return view('patients.print',compact('patient'));
    }

    public function export(Patient $patient)
    {
        $patient=$patient::where('id',$patient->id)->get();

        return Excel::download(new PatientExport($patient), 'patient.xlsx');
    }
}

resources/views/patients/action.blade.php
<td>
    <div class="d-flex">
    <a href="{{ route('patients.show', $patient) }}" title="View Record">
        <i class="mdi mdi-eye" style="width: 1px"></i>
    </a>
    <a href="{{ route('patients.edit', $patient) }}" title="Edit Record">
        <i class="mdi mdi-grease-pencil" style="color: orange"></i>
    </a>
    <a href="#!"
       onclick="confirm('{{ __("Are you sure you want to delete this item?") }}') ?  document.getElementById('delete-patient').submit() : ''">
        <i class="mdi mdi-delete" style="color: red" title="Delete Record">

        </i>
    </a>

    <form action="{{ route('patients.destroy', $patient) }}" method="post" id="delete-patient">
        @csrf
        @method('DELETE')
    </form>
    <a href="{{route('patients.print',$patient)}}" title="Print Record">
        <i class="mdi mdi-cloud-print-outline" style="color: saddlebrown"></i>
    </a>

    <a href="{{route('patientExport',$patient)}}" title="Export Record"><i class="mdi mdi-export" style="color: green"></i></a>
    </div>
</td>

resources/views/patients/create.blade.php
@extends('layouts.patients.app')
@section('title')
    Create Record
@endsection
@section('content')
    <form method="post" action="{{route('patients.store')}}" enctype="multipart/form-data">
        @csrf
        @include('patients.form')
    </form>
@endsection

resources/views/patients/edit.blade.php
@extends('layouts.patients.app')
@section('title')
    Edit Record
@endsection
@section('content')
    <form method="post" action="{{route('patients.update',$patient)}}" enctype="multipart/form-data">
        @csrf
        @method('patch')

        @include('patients.form')

    </form>
@endsection

resources/views/patients/filter.blade.php
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Filter Patient</h4>
            <form class="form-inline">
                <label class="sr-only" >Age</label>
                <input type="number" class="form-control mb-2 mr-sm-2" name="min_age"  value="{{ $activefilters['min_age'] ?? '' }}" placeholder="Min Age">
                <input type="number" class="form-control mb-2 mr-sm-2" name="max_age"  value="{{ $activefilters['max_age'] ?? '' }}" placeholder="Max Age">

                <label class="sr-only" for="medical_examination_date" >Medical Examination Date</label>
                <input type="date" class="form-control mb-2 mr-sm-2 date" value="{{ $activefilters['from'] ?? '' }}" name="from" placeholder="From">
                <input type="date" class="form-control mb-2 mr-sm-2 date" value="{{ $activefilters['to'] ?? '' }}" name="to"  placeholder="To">

                <label class="sr-only" for="gender">Gender</label>
                <div class="input-group mb-2 mr-sm-2">
                    <select class="form-control " name="gender"  id="gender" >
                        <option value=" ">Select Gender</option>
                        <option value="Male" {{ ($activefilters['gender'] ?? '') == "Male" ? 'selected' : '' }}>Male</option>
                        <option value="Female" {{ ($activefilters['gender'] ?? '') == "Female" ? 'selected' : '' }}>Female</option>
                    </select>
                </div>
                <div class="input-group mb-2 mr-sm-2">
                    <select class="form-control " name="status"  id="status" >
                        <option value=" ">Select Status</option>
                        <option value="FIT" {{ ($activefilters['status'] ?? '') == "FIT" ? 'selected' : '' }}>FIT</option>
                        <option value="UNFIT" {{ ($activefilters['status'] ?? '') == "UNFIT" ? 'selected' : '' }}>UNFIT</option>
                    </select>

                </div>

                <button type="submit" class="btn btn-primary mb-2">Filter</button>
            </form>
        </div>
    </div>
</div>

resources/views/patients/index.blade.php
@extends('layouts.app')
@section('title')
    Patients Records
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
                <div class="d-flex align-items-end flex-wrap">
                    <div class="mr-md-3 mr-xl-5">
                        <div class="d-flex">

                            <a class="text-muted mb-0 hover-cursor" href="{{route('home')}}">  <i class="mdi mdi-home text-muted hover-cursor"></i>Dashboard/&nbsp;</a>
                            <p class="text-primary mb-0 hover-cursor">Patient Records</p>
                        </div>
                    </div>
                </div>
            <div class="d-flex justify-content-between align-items-end flex-wrap float-right">
                <button class="btn btn-light bg-white btn-icon mr-3 d-none d-md-block" id="filter_sign" title="Filter"><i class="mdi mdi-filter"></i></button>
            </div>
        </div>
        <div class="filter-section">
            @include('patients.filter')
        </div>
            <br>
        @include('layouts.alert.alert')
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="card-top">
                    <h4 class="card-title">{{ __('Patients Record') }}</h4>
                    <div class="card-description" >
                                <a href="{{route('patients.create')}}" class="btn btn-primary btn-icon-text">Create <i class="mdi mdi-plus"></i> </a>
                    </div>
                </div>
{{--                    close card-top--}}
                    <div class="table-responsive">
                        {{$dataTable->table(['class' => 'table table-hover'])}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('style')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <style>
        .card-top{
            display: flex;
            justify-content: space-between;
        }
        .card-top .card-description a {
            width: 117px;
            border-radius: 31px;
            background-color: #e73b3b;
            border: 0;
            padding: 10px;
            padding-top: 5px;
        }

         .d-flex .mdi{
             padding-right:15px;
             text-align: center;
         }
        .odd tr{
            text-align: center;
            vertical-align: middle;
        }
        .table hover th{
            white-space: nowrap;
        }
    </style>
@endsection
@section('script')
    <script src="{{ asset('/vendor/datatables/buttons.server-side.js') }}"></script>
    {{$dataTable->scripts()}}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        var fp = flatpickr(".date", {
            dateFormat: "Y-m-d",
        })
    </script>
@endsection

resources/views/patients/show.blade.php
@extends('layouts.patients.app')
@section('title')
    View Record
@endsection
@section('content')
    <div class="table table-head">

    <table class="table-wrap">
        <p style="vertical-align: middle; text-align: center; border: 1px solid #ddd;  width:100px;  padding: 5px; margin: auto; font-weight: bold;" >{{ $patient->status ?? null }}</p>
        <thead>
        <tr>
            <th>EMC Code 1153</th>

            <th></th>
            <th>Medical Examination Date: {{ isset($patient) ? date("Y-m-d", strtotime($patient->medical_examination_date)):date("Y-m-d") }}</th>
        </tr>
        </thead>

        <tbody>
        <tr>
            <td>  <label>SEX:{{ __('Name') }} : {{$patient->name ?? null}}</label> </td>
            <td><label>SEX:{{ __('Marital Status') }} : {{$patient->marital_status ?? null }}</label></td>
            <td><label>SEX:{{ __('Apply Country') }} : {{$patient->apply_county  ?? null }}</label> </td>
        </tr>
        <tr>
            <td><label>SEX:{{ __('Age') }} : {{$patient->age  ?? null }}</label> </td>
            <td><label>SEX:{{ __('Nationlity') }} : {{$patient->nationality  ?? null }}</label> </td>
            <td><label>SEX:{{ __('PP:Issue date & place') }} : {{$patient->pp_issue_date  ?? null }} at {{$patient->pp_issue_place  ?? null }}</label></td>
        </tr>
        <tr>
            <td><label>SEX:{{ __('SEX') }} : {{$patient->sex  ?? null }}</label></td>
            <td><label>SEX:{{ __('PP NO:') }} : {{$patient->pp_no  ?? null }}</label></td>
            <td><label>SEX:{{ __('Recruiting Agency:') }} : {{$patient->recruiting_agency  ?? null }}</label></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="table table-head">

    <table class="table-wrap">
        <p style="vertical-align: middle; border: 1px solid #ddd; padding-left: 10px;" >Post history of setous lines and major surgery : {!!  $patient->history_illness ?? null !!}</p>

        <tbody>
        <tr>
            <td> <label>{{ __('Height:') }} : {{$patient->height  ?? null }}</label> </td>
            <td><label>{{ __('Pulse') }} : {{$patient->pulse  ?? null }}</label> </td>
            <td><label>{{ __('Jaundice') }} : {{$patient->jaundice  ?? null }}</label> </td>
            <td><label> {{ __('Ascites') }} : {{$patient->ascites  ?? null }}</label> </td>
            <td><label> {{ __('Lymph Node') }} : {{$patient->lymph_node  ?? null }}</label> </td>
        </tr>
        <tr>
            <td><label>{{ __('Weight') }} : {{$patient->weight  ?? null }}</label></td>
            <td><label>{{ __('BP') }} : {{$patient->bp  ?? null }}</label></td>
            <td><label>{{ __('Oedema') }} : {{$patient->oedema  ?? null }}</label></td>
            <td><label>{{ __('Allergy') }} : {{$patient->allergy  ?? null }}</label> </td>
            <td><label>{{ __('Fungal infection') }} : {{$patient->fungal_infection  ?? null }}</label></td>
        </tr>
        <tr>
            <td><label>{{ __('Temperature')}} : {{$patient->temp  ?? null }} </label></td>
            <td><label>{{ __('Clubbing')}} : {{$patient->clubbing  ?? null }}</label></td>
            <td><label>{{ __('Paller')}} : {{$patient->paller  ?? null }}</label></td>
            <td><label>{{ __('Cyanosis')}} : {{$patient->cyanosis  ?? null }}</label></td>
            <td><label>{{ __('Epilepsy/Depression')}} : {{$patient->depression  ?? null }}</label></td>
        </tr>

        </tbody>
    </table>
</div>
<div class="left-side">
    <div class=" table-side">
        <table class=" table ">
            <p style="vertical-align: middle; text-align: center; border: 1px solid #ddd;background: #000; width: 200px; color: #fff; padding: 5px; font-weight: bold;" >SYSTRMIC EXAMINATION </p>
            <thead>
            <th colspan="2">Type of Examination</th>

            <th>Result</th>
            </thead>
            <tbody>
            <tr valign="center" style="border: 1px solid #ddd;" >
                <td rowspan="3" style="vertical-align: middle; border-right: 1px solid #ddd;" >Eye Vision</td>
                <td>R.Eye</td>
                <td>{{$patient->right_eye  ?? null }}</td>
            </tr>
            <tr>

                <td>L.Eye</td>
                <td>{{$patient->left_eye  ?? null }}</td>

            </tr>
            <tr>

                <td>Color Vission</td>
                <td>{{ $patient->color_vision  ?? null }}</td>

            </tr>
            <tr valign="center" >
                <td rowspan="2" style="vertical-align: middle;" >Ear</td>
                <td>R.Ear</td>
                <td> {{ $patient->right_ear  ?? null }}</td>

            </tr>
            <tr>

                <td>L.Ear</td>
                <td>{{ $patient->left_ear  ?? null }}</td>

            </tr>
            <tr>
                <td colspan="2">Cordiovascular</td>
                <td>{{ $patient->cardiovascular ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Pulrnonary</td>
                <td>{{  $patient->pulmonary ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Gastroenterology</td>
                <td>{{  $patient->gastroenterology ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Neorology</td>
                <td>{{  $patient->neurology ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Museulosheletal</td>
                <td>{{ $patient->musculoskeletal ?? null }} </td>
            </tr>
            <tr>
                <td colspan="2">Genitounnary</td>
                <td>{{ $patient->genitourinary ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Ore-Dentel</td>
                <td>{{ $patient->oro_dental ?? null }} </td>
            </tr>
            <tr>
                <td colspan="2">Extremilies/Deformities</td>
                <td>{{ $patient->extremities ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Varicose Veins</td>
                <td>{{ $patient->varicose_veins ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Hernia</td>
                <td>{{ $patient->hernia ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Hydrocele</td>
                <td>{{$patient->hydrocele ?? null }}</td>
            </tr>
           {{-- <tr>
                <td colspan="2">Hydrocele</td>
                <td>{{ $patient->hydrocele ?? null }}</td>
            </tr>--}}
            <tr>
                <td colspan="2">Radiological(Chest X-ray)</td>
                <td>{{  $patient->radiological ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">ECG</td>
                <td>{{ $patient->ecg ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Heart</td>
                <td>{{ $patient->heart ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Lungs</td>
                <td>{{ $patient->lungs ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Abidamon</td>
                <td>{{ $patient->abdomen ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2">Clinical Impression</td>
                <td>{{ $patient->clinical_impression ?? null }}</td>
            </tr>

            </tbody>

        </table>
    </div><!-- close table-side -->
    <p class="mention">{{$patient->name}} is {{$patient->status}} for the Mentioned job.</p>
</div>
<div class="right-side">
    <div class="table-resposive">
        <p style="vertical-align: middle; text-align: center; border: 1px solid #ddd; background: #000; width:200px; color:#fff; padding: 5px; font-weight: bold;" >LABORATORY EXAMINATION</p>
        <table class="table">

            <p style="vertical-align: middle; text-align: center; border: 1px solid #ddd; font-weight: bold;" >Serology</p>

            <thead>
            <th>Examination</th>
            <th style="text-align: center;">Result</th>
            </thead>
            <tbody>
            <tr>
                <td>Anti-HIV(1&2)</td>
                <td>{{ $patient->anti_hiv ?? null }}</td>
            </tr>
            <tr>
                <td>HBS-AQ </td>
                <td>{{ $patient->hbs_ag ?? null }} </td>
            </tr>
            <tr>
                <td>Anti-HCV  </td>
                <td>{{ $patient->anti_hcv ?? null }}</td>
            </tr>
            <tr>
                <td>VDRL  </td>
                <td>{{  $patient->vdrl ?? null }} </td>
            </tr>
            <tr>
                <td>TPHA</td>
                <td>{{ $patient->tpha ?? null }} </td>
            </tr>
            <tr>
                <td>Blood Group(ABO/Rh)</td>
                <td>{{ $patient->blood_group ?? null }}</td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;"><strong>Urine</strong></td>
            </tr>
            <tr>
                <td>RBC</td>
                <td> {{$patient->rbc ?? null }}</td>
            </tr>
            <tr>
                <td>Pus Cells</td>
                <td>{{  $patient->pus_ceils ?? null }}</td>
            </tr>
            <tr>
                <td>Bacteria</td>
                <td> {{ $patient->bacteria ?? null }}</td>
            </tr>
            <tr>
                <td>Opiates</td>
                <td>{{  $patient->opiates ?? null }} </td>
            </tr>
            <tr>
                <td>Epithelial Cells</td>
                <td>{{  $patient->epithelial_cells ?? null }} </td>
            </tr>
            <tr>
                <td>Pregnancy Test (If Female)</td>
                <td>{{  $patient->pregnancy_test ?? null }}</td>
            </tr>

            </tbody>
        </table>
    </div><!-- table-resposive-->
    <div class="table-resposive">
        <table class="table">

            <p style="vertical-align: middle; border: 1px solid #ddd; font-weight: bold; margin-bottom: 0;  padding: 5px; background: #000; color: #fff; width: 130px;" >HEMATOLOGY</p>

            <thead>
            <th>Blood Examination</th>
            <th style="text-align: center;">Result</th>
            <th>Reference range</th>
            </thead>
            <tbody>
            <tr>
                <td>Total/WBC Count</td>
                <td>{{  $patient->total_wbc_count ?? null }}</td>
                <td>4000-11000</td>
            </tr>
            <tr>
                <td>Neutrophils</td>
                <td>{{ $patient->neutrophils ?? null }}</td>
                <td>45-74%</td>
            </tr>
            <tr>
                <td>Lymphocytes</td>
                <td>{{ $patient->lymphocytes ?? null }} </td>
                <td>25-40%</td>
            </tr>
            <tr>
                <td>Eosinophils</td>
                <td>{{  $patient->eosinophils ?? null }}</td>
                <td>1-6%</td>
            </tr>
            <tr>
                <td>Monocytes</td>
                <td>{{ $patient->monocytes ?? null }}</td>
                <td>0-8%</td>
            </tr>
            <tr>
                <td>Basophils</td>
                <td>{{ $patient->basophils ?? null }}</td>
                <td>0-3%</td>
            </tr>
            <tr>
                <td>ESR</td>
                <td>{{ $patient->esr ?? null }}</td>
                <td>M<10,F<20</td>
            </tr>
            <tr>
                <td>Hemoglobin</td>
                <td>{{ $patient->hemoglobin ?? null }}</td>
                <td>M 12-17 gm% <br> F 11-14 gm%</td>
            </tr>
            <tr>
                <td>Malaria Parasite</td>
                <td>{{ $patient->malaria_parasite ?? null }}</td>
                <td></td>
            </tr> <tr>
                <td>Micro Filaria</td>
                <td>{{ $patient->micro_filaria ?? null }}</td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div><!-- table-resposive-->

    <div class="table-resposive">
        <table class="table">

            <p style="vertical-align: middle; border: 1px solid #ddd; font-weight: bold; margin-bottom: 0;  padding: 5px; background: #000; color: #fff; width: 130px;" >BIOCHEMISTRY</p>

            <thead>
            <th>Randan Blood Sugar</th>
            <th>{{ $patient->random_blood_sugar ?? null }} </th>
            <th>80-30mg%</th>
            </thead>
            <tbody>
            <tr>
                <td>Urea</td>
                <td>{{ $patient->urea ?? null }}</td>
                <td>20-25mg%</td>
            </tr>
            <tr>
                <td> Crealnine</td>
                <td>{{ $patient->creatinine ?? null }}</td>
                <td>04-14mg%</td>
            </tr>
            <tr>
                <td> Total Direct</td>
                <td>{{  $patient->bilirubin ?? null }} </td>
                <td>0.4-1mg%</td>
            </tr>
            <tr>
                <td>SGPT</td>
                <td>{{ $patient->sgpt ?? null }} </td>
                <td>5-37 UL</td>
            </tr>
            <tr>
                <td>SGOT</td>
                <td>{{  $patient->sgot ?? null }}</td>
                <td>5-37 UL</td>
            </tr>

            <tr>
                <td colspan="3" style="text-align: center"><strong>Other</strong></td>

            </tr>
            <tr>
                <td>Cannabis</td>
                <td colspan="2">{{$patient->cannabis ?? null }}</td>
            </tr>
            <tr>
                <td>Mantoex</td>
                <td colspan="2">{{ $patient->mantoux_test ?? null }}</td>
            </tr>
            </tbody>
        </table>
    </div><!-- table-resposive-->
</div>
<div class="clear"></div>
<p class="text-contain">This Report is vaild for 2 month the date of medical Examination DR.Nabin Kumar chaudhary</p>

<a href="{{route('patients.print',$patient)}}">Print</a>
@endsection